replicaCount: 1

image:
  repository: nginx
  tag: 1.19
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

env:
  ENVIRONMENT: dev

labels:
  app.kubernetes.io/managed-by: argocd