apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: file:///tmp/helm-charts  # For demo, would be a Git repo in production
    targetRevision: HEAD
    path: simple-app
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: fullnameOverride
          value: app1
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true